STARTERS = {
    1: ("Bulbasaur", "Charmander", "Squirtle"),
    2: ("Chikorita", "Cyndaquil", "Totodile"),
    4: ("Treecko", "Torchic", "Mudkip"),
    5: ("Turtwig", "Chimchar", "Piplup"),
    6: ("Snivy", "Tepig", "Oshawott"),
    7: ("Chespin", "Fennekin", "Froakie"),
    8: ("Rowlet", "Litten", "Popplio"),
    9: ("Grookey", "Scorbunny", "Sobble"),
}

NATURES = [
    "Adamant",
    "Bashful",
    "Bold",
    "Brave",
    "Calm",
    "Careful",
    "Docile",
    "Gentle",
    "Hardy",
    "Hasty",
    "Impish",
    "Jolly",
    "Lax",
    "Lonely",
    "Mild",
    "Modest",
    "Naive",
    "Naughty",
    "Quiet",
    "Quirky",
    "Rash",
    "Relaxed",
    "Sassy",
    "Serious",
    "Timid",
]
